### ISSUE TITLE
Add existing SteamLibrary (or create one) outside of /home/$USER

### ISSUE THREAD

**Issue by mainmachine** [snapcrafters/steamforwindows#1]
Great SNAP you've got here! :)

I had an existing steam library folder so I could experiment with different wineprefixes without having to duplicate the game data, but it lives on a secondary drive I've got mounted outside of /home/$USER so this snap can't access it.

Would I just need to install this with --classic to allow this to work, or is there a really good reason I shouldn't do that?

**Comment by popey** [comment]
Yeah, don't install non-classic snaps with --classic. That won't work out well. Where is the folder located? We could the `removable-media` plug, which would enable access to directories under `/media` and `/run/media`.

**Comment by mainmachine** [comment]
I'll admit it's probably a bad habit, but for secondary drives I'd make a mountpoint off of root and then manage permissions of subfolders separately.

If the folder was in ~/ then it should be accessible to the snap, avoiding this problem, correct?

Disclaimer: I've only done this on my own personal systems, and just been too lazy to remount in a more sensible place like /mnt or even somewhere in ~/ - in production I mount in a sensible manner. :)

**Comment by popey** [comment]
I don't think you can circumvent the security model with a symlink ;).

You can mount the same partition twice though. So for your muscle memory lazy brain, leave the old mount point. For your new snap future, use the "standard" one.

**Comment by mainmachine** [comment]
Ah, that's a fantastic point, and one I'd forgotten as usually there's no need to make more than one mount point.

I will try it and close this issue, as it's kind of a fringe request anyway. :)
